### ISSUE TITLE
Question about non working day that is not a public holiday

### ISSUE THREAD

**Issue by DanielSundberg** [martinjw/Holiday#10]
I was going to create a patch that add Swedish public holidays. However, it appears that I don't know much about how holidays and days off work in other countries. In Sweden we have two "classes" of holidays:

1. Public holidays, days off, "red days" in the calendar, usually treated as a Sunday regarding store opening hours and other community services.
2. Holiday eves, some treated as a Saturday and everyone's off work (Christmas eve, Midsummer eve), other are treated as a week day (MaundyThursday, Epihany eve) but Saturday rules apply in some cases (for example car parking). Depending on your employer different rules apply, about 50% of the workers only work 4 hours.

Since I will be using this library to query if a specific day is on or off work I would need a <code>IsDayOffWork()</code> method rather then the <code>IsPublicHoliday()</code> method.

Would it be ok to add this or perhaps the <code>IsDayOffWork()</code> belongs in another library and this is only for public holidays?

Readme talks about <code>IsBankHoliday()</code> method in <code>IPublicHolidays</code> but it doesn't seem to exist in master? That's probably a more suited method for my case?

**Comment by martinjw** [comment]
The rules vary by country, but a few countries have normal public holidays and additional "bank holidays" (banks and government offices are closed, but most private companies are open). 

Conversely, the UK calls all public holidays "bank holidays" (so UKBankHoliday has a IsBankHoliday() method as well as a IsPublicHoliday())

My suggestion would be use IsPublicHoliday() for the main "red days" (non-working day for most people), then add a custom method for the "eves" (may be non-working or half day depending on employer)- maybe IsHalfDay() or IsEve().

**Comment by DanielSundberg** [comment]
Ok, sounds like a great approach. I'll try to find time to create a pull request.
