### ISSUE TITLE
Please add targets for .net standard 2.0 and/or 2.1

### ISSUE THREAD

**Issue by bantza** [martinjw/Holiday#101]
Could you add targets for .net standard 2.0 and/or 2.1 for the next release?

I had a .net standard 2.1 library using this package and on the solution using that library I got a lot of NU1605 detected package downgrade errors when publishing, because Holiday package was including old version of NETstandard.library to the build.

I have built the holiday package my self from the source in this repo targeting .net standard 2.1 (and only that, didn't want to install extra SDKs for other targets) and my solution publishes fine with it.

**Comment by martinjw** [comment]
See the pre-release here https://github.com/martinjw/Holiday/releases/tag/2.29.1.0
