### ISSUE TITLE
UK Christmas/Boxing day incorrect if Christmas on Sunday

### ISSUE THREAD

**Issue by Spetsen** [martinjw/Holiday#105]
If Christmas day is on a Sunday (and therefore Boxing day on Monday) the observed date for Christmas day should be the Tuesday according to https://www.gov.uk/bank-holidays (see 2022), with Boxing day being observed on the Monday. This library puts Christmas day on the Monday and moves Boxing day to Tuesday.

I'm willing to create a PR with a fix for this if you'd like me to.

**Comment by martinjw** [comment]
So in some years, Boxing Day is before Christmas day... hmm. If you'd like to do a PR, it would be very welcome!

**Comment by Spetsen** [comment]
I agree that it's a bit strange that Boxing Day happens before Christmas day. I'm guessing the reasoning is that it's more "correct" when one of the days can be on its "original" date. Anyways, PR created. 😄
