### ISSUE TITLE
IrelandPublicHoliday.StBrigid returns the wrong day if 1st of February is a Friday

### ISSUE THREAD

**Issue by Bjornsen016** [martinjw/Holiday#110]
Taken from [here](https://www.citizensinformation.ie/en/employment/employment-rights-and-conditions/leave-and-holidays/public-holidays/#lc3a51).
It should be the 1st of February if the 1st of February is a Friday.

I can make a PR to fix this if you want to.

**Comment by martinjw** [comment]
Yep, please do a PR, thanks!
