### ISSUE TITLE
IrelandPublicHoliday considers weekends when it shouldn't

### ISSUE THREAD

**Issue by Bjornsen016** [martinjw/Holiday#111]
From my understanding the following Public Holidays in Ireland does not move if there is a weekend.
- New Year's Day (1 January)
- Saint Patrick's Day (17 March)
- Christmas Day (25 December)
- Saint Stephen's Day (26 December)
Right now IrelandPublicHoliday uses HolidayCalculator.FixWeekend on all of these.

MayDay in Ireland should be the First Monday in May. As of now IrelandPublicHoliday takes 1 May (with weekend fix). 

All of the info above is taken from the link below.
https://www.citizensinformation.ie/en/employment/employment-rights-and-conditions/leave-and-holidays/public-holidays/#lc3a51

I can make a PR to fix this if you want to.

**Comment by martinjw** [comment]
Agreed, Monday rules apply only to St Brigid, Easter, May day, June, August, October holidays. 
PR would be welcome! Thanks
