### ISSUE TITLE
Missing good Friday

### ISSUE THREAD

**Issue by wdnijdam** [martinjw/Holiday#118]
In Dutch companies optionally Good Friday is used as public holiday. This is the Friday before easter.

Optionally add

```
    /// <summary>
    /// "Good Friday" / "Goede Vrijdag"
    /// </summary>
    /// <remarks>It depends on the company if Good Friday is a free holiday</remarks>
    internal static DateOnly GoodFriday(DateOnly easterSunday)
    {
        return easterSunday.AddDays(-2);
    }
```

The same is true for Bridging days (days enclosed between the weekend and a public holiday) like the Friday after  Ascension day / Hemelvaartsdag

**Comment by martinjw** [comment]
Added, just as a public static method on DutchPublicHoliday class. Bridge days seem unfortunately random, some years there are lots of candidate Monday/Tuesdays, some years there are few.
