### ISSUE TITLE
AustriaPublicHoliday.IsPublicHoliday

### ISSUE THREAD

**Issue by oliver-h** [martinjw/Holiday#12]
Hello there,

I was about to use your nice and useful lib and did some validation prior to that. I found a little bug:

The following code snippet will print the dates 30.5.2013 and 26.5.2016 (Corpus Christi), which should not happen:

```cs
var h = new AustriaPublicHoliday();

for (int year = 2010; year < 2018; year++)
{
    var days = h.PublicHolidays(year);
    var fd = days.Where(d => !h.IsPublicHoliday(d));

    if (fd.Any())
        Console.WriteLine(string.Join(Environment.NewLine, fd));
}
```
Wouldn't it be easier to use the PublicHolidays list to check against a single date in the IsPublicHolday method?

Best regards,
Oliver

**Comment by martinjw** [comment]
The reason IsPublicHoliday doesn't use the list is for performance. If you hit that method a lot, and it creates the full list for the year each time, it starts rising up the profiler hot spots list. Obviously it's even more efficient to grab the list from PublicHolidays and directly check against that.
