### ISSUE TITLE
For Turkey public holidays wrong Ramadan and FeastOfSacrifices holidays calculations

### ISSUE THREAD

**Issue by hasankaplan-github** [martinjw/Holiday#125]
Hi,
For Turkey public holidays, Ramadan holidays and FeastOfSacrifices holidays calculations are not completely correct for some years. In one Gregorian year, 2000 or 2033 for example, two Ramadan holidays may exist (in January and in December.) To cover that case `GetHijriYear()` method and `Ramadan` and `FeastOfSacrifices` holidays methods should return multiple results. Below is my solution:

```
private IEnumerable<int> GetHijriYears(int year)
{
    var diff = year - 621;
    var hijriYear = Convert.ToInt32(Math.Round(diff + decimal.Divide(diff, 33), MidpointRounding.ToZero));
    return [hijriYear, hijriYear + 1];
}

public IEnumerable<DateTime> RamadanFirstDay(int year)
{
    var hijriCalendar = new UmAlQuraCalendar();
    var hijriYears = GetHijriYears(year);

    foreach (var hijriYear in hijriYears)
    {
        var dateTime = hijriCalendar.ToDateTime(hijriYear, 10, 1, 0, 0, 0, 0);
        if (dateTime.Year != year)
        {
            continue;
        }

        yield return dateTime;
    }
}
```

**Comment by martinjw** [comment]
Released in https://github.com/martinjw/Holiday/releases/tag/2.39.0.0

**Comment by hasankaplan-github** [comment]
Hi,
I had suggested solution above, but this solution gives wrong results for some years. In Turkiye, Presidency of Religious Affairs (Diyanet İşleri Başkanlığı) determines the religious holiday dates. So you can get correct holiday dates from the web site which is in Turkish: "https://vakithesaplama.diyanet.gov.tr/dinigunler.php?yil=2026". Also the correct calculation reference can be found in "https://github.com/nager/Nager.Date" repo.
