### ISSUE TITLE
Add a French version without PentecostMonday as it maybe a working day

### ISSUE THREAD

**Issue by bhugot** [martinjw/Holiday#134]
Hello,

Would it be possible de have a way to exclude a specific day like PentecostMonday at will.
In France PentecostMonday can be a working day as a Solidarity Day

Regards

**Comment by martinjw** [comment]
Yes, we have private methods like HasHolidayX() used for the different regions. We could simply have a public property bool HasPentecostMonday; set it to false and the instance methods don't return the holiday.
