### ISSUE TITLE
Bavarian Holiday Assumption is not valid in all of Bavaria

### ISSUE THREAD

**Issue by mrutsch** [martinjw/Holiday#135]
Hello @martinjw,

we use your PublicHoliday package in our application and appreciate your hard work! 

In issue #104, there was a change, adding Assumption for all of Bavaria, even though the map shows that it is not valid everywhere. This holiday is only for parts of Bavaria that are inhabited by a majority of catholics, so it can actually change over time. 

It would be great if you could revert this commit again or maybe add a differentiation between catholic and non-catholic parts of Bavaria. Thanks!

**Comment by martinjw** [comment]
I can make the HasAssumption getter have a setter to manually override. Like this...
```c#
            //assumption is 15/08/2024
            var calendar = new GermanPublicHoliday { State = GermanPublicHoliday.States.BY };
            var isHoliday = calendar.IsPublicHoliday(assumption); //true
           //the getter
            var hasAssumption = calendar.HasAssumption; //true
            //override the default - make it false
            calendar.HasAssumption = false;
           //now the calendar does not think assumption is a holiday
            isHoliday = calendar.IsPublicHoliday(assumption); //false
```

**Comment by martinjw** [comment]
You have to know you are in a catholic or non-catholic region and change it manually - but this would give you the flexibility to do this, and change it dynamically within Bavaria.

**Comment by mrutsch** [comment]
Thanks, this would be good enough for us.

**Comment by martinjw** [comment]
Fixed in https://github.com/martinjw/Holiday/releases/tag/2.40.0.0  now on nuget

**Comment by rm-code** [comment]
@martinjw Can you maybe elaborate on the assumption handling? Maybe I'm misunderstanding, but doesn't this override the assumption state for the full holiday handling and not just this one particular holiday? We hit this issue in production, but I'm worried that setting the assumption to false will cause other side-effects. Thanks.
