### ISSUE TITLE
Include Anniversary days in NZ?

### ISSUE THREAD

**Issue by louiszhuang** [martinjw/Holiday#24]
just notice Anniversary days are missing in NZPublicHoliday. should we add them?

**Comment by shanerogers** [comment]
Sounds good. I didn’t need them as it wall only about national non banking
days.

**Comment by seancallinan** [comment]
@louiszhuang @martinjw Should be able to close this now?

**Comment by martinjw** [comment]
Fixed in https://github.com/martinjw/Holiday/releases/tag/2.17.0.0
