### ISSUE TITLE
Public Holidays in Germany

### ISSUE THREAD

**Issue by ratinhoo** [martinjw/Holiday#28]
Hi,

first of all thanks to your great library.

I have found two problems in german holiday recognition.

1. Apparently Easter Sunday and Whit Sunday are public holidays in Brandenburg (BB)

2. Each Sunday is a public holiday in Hessen (HE)

**Comment by martinjw** [comment]
Thanks for the feedback

These are Sundays- technically not holidays, but by convention and law not (normal) business days either (in the German Constitution, Art 139, Der Sonntag und die staatlich anerkannten Feiertage bleiben als Tage der Arbeitsruhe und der seelischen Erhebung gesetzlich geschützt.) 

Using the standard business working week, the list of public holidays is those that occur on Monday-Friday, excluding the weekends.

**Comment by ratinhoo** [comment]
It is absolutely possibly that a public holiday (in german: Gesetzlicher Feiertag) is on a Saturday or Sunday. All overviews of the public holidays in Germany, which I can find in the internet, state that Easter Sunday and Whit Sunday are public holidays in Brandenburg (BB).

The following link shows the law of the state Hessen that points out that each Sunday is a public holiday in Hessen. 
http://www.datumsrechner.de/gesetze/Hessen.pdf

**Comment by martinjw** [comment]
Yes, I agree. In all countries the New Year (if it is a holiday) is 1 January, whether that is a weekday or a Saturday or Sunday. 

This library works for holidays for a specific definition of the standard working week - Monday-Friday - that is the convention for most of the world. This is useful for businesses. It is not a general calendar generator, which would make it more complicated...

If I want to do a money transfer, I want to do it on banking/regular working days, Monday-Friday but not on public holidays. The library helps the scheduler pick those days (hence methods like NextWorkingDay()). Even in public transport which runs every day, a holiday schedule is usually a Sunday schedule, so Easter Sunday isn't meaningfully different to any Sunday. 

The distinction is particularly important in countries that use substitution days, adding a new day when the actual date is a weekend. The library will show NewYear that is not 1 January; in a strict sense it always is, but there is an "extra" holiday observed with the same name. There's also a complication for countries that "faire le pont" ("make the bridge") when Tuesday/Thursday holidays become a 4-day weekend- guessable with extra code.

Calendars are pretty complicated, so we're taking a narrow definition here- based on the conventional business working week. 

Hope this explains why it works this way!

**Comment by ratinhoo** [comment]
Yes, public holidays are quite (unnecessary) complicated. Thanks for your explanation.
