### ISSUE TITLE
Additional bank holidays in Germany

### ISSUE THREAD

**Issue by janaw** [martinjw/Holiday#39]
Last year a few german states added the reformation day as bank holiday. These should be added to the Array.

public bool HasReformation => Array.IndexOf(new[] { States.BB, States.MV, States.SN, States.ST, States.TH, States.HB, States.HH, States.NI, States.SH}, State) > -1;

Source: https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland

**Comment by janaw** [comment]
And Thüringen got a new one as well, 28th Feb is now World Children´s Day. 

Source: https://de.wikipedia.org/wiki/Kindertag

"Am 28. Februar 2019 beschloss der Landtag von Thüringen mit den Stimmen der rot-rot-grünen Mehrheit, dass ab sofort der Weltkindertag am 20. September ein gesetzlicher Feiertag ist.[21]"

**Comment by martinjw** [comment]
Pushed to nuget as v2.0.7. Thanks for the information!
