### ISSUE TITLE
Exception thrown when getting the holidays for Japan in 2020

### ISSUE THREAD

**Issue by overstimulated** [martinjw/Holiday#43]
When getting the PublicHolidayNames(2020) for Japan, this exception is thrown

`An item with the same key has already been added. Key: 5/4/2020 12:00:00 AM`

Reason:
ConstitutionMemorialDay(2020) is set to May 3 which is moved to May 4 because May 3 is a Sunday.
GreeneryDay(2020) is already set to May 4 which causes the exception to be thrown

**Comment by martinjw** [comment]
Nuget package updated. Thanks!
