### ISSUE TITLE
Get IPublicHoliday by culture code

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [martinjw/Holiday#48]
Is there any way to retrieve an `IPublicHoliday` based on a culture code like `en-US`?

**Comment by martinjw** [comment]
It would be easy to write a simple factory method that did this.
```c#
        public IPublicHolidays Factory(CultureInfo culture)
        {
            switch (culture.Name)
            {
                case "en-US":
                    return new USAPublicHoliday();
                case "en-CA":
                    return new CanadaPublicHoliday();
                case "en-GB":
                    return new UKBankHoliday();
                default:
                    throw new InvalidOperationException("Culture not known or specified");
            }
        }
```
It becomes a bit more complex if you're dealing with regions (as in Canada), multi-language countries (Canada again), and regions that don't have an ISO culture code (Scotland, which has Scottish Gaelic gd-GB but not en-scot). 

Also this library isn't really localized- hol.PublicHolidayNames() returns local names in the majority local language, but not language and regional variations (one exception is Belgium, where I did Flemish and French methods- and I still skipped German). To do this properly (and perhaps add language neutral variants) would be a major effort.

**Comment by gabriele-ricci-kyklos** [comment]
All right, I thought that there might be something already built-in into the lib but I'll do something as you described
