### ISSUE TITLE
Move IPublicHolidays to separate nuget package

### ISSUE THREAD

**Issue by konradbartecki** [martinjw/Holiday#50]
Hey, I have a minor issue, where I am building a feature in another public NuGet package that would optionally take `IPublicHolidays` as parameter.

Right now I would have to reference the whole Holiday package, but I actually only need to reference `IPublicHolidays` interface.

**Would it be possible to move `IPublicHolidays` to a separate NuGet like `Holiday.Interfaces` or `Holiday.Model`?**

I assume the main NuGet package `Holiday` would later depend on this newly created NuGet package.

**Comment by martinjw** [comment]
It seems odd to have a nuget package/dll with just one interface, when the entire holiday package/dll isn't that big to start with... It may give the impression the library is more complicated than it is?

**Comment by konradbartecki** [comment]
If you say so I'll agree with you 😄 sounds fair enough. Thanks, I'll close this ticket.
