### ISSUE TITLE
Canada has added National Day for Truth and Reconciliation, September 30th 

### ISSUE THREAD

**Issue by mattandwhatnot** [martinjw/Holiday#53]
National Day for Truth and Reconciliation day is a new paid Federal holiday with the fixed date of September 30th from 2021 onwards. 

Not all provinces are observing but federally regulated industries are regardless of province (similar to Remembrance Day). Although, many cities (city employees) in non-observing provinces _are_ observing.

**Comment by martinjw** [comment]
Thanks, released in 2.7.0!
