### ISSUE TITLE
Netherlands and Estonia are missing

### ISSUE THREAD

**Issue by Stefan-Yordanov** [martinjw/Holiday#63]
It looks the implementations for Netherlands and Estonia are missing are they not supported anymore

**Comment by martinjw** [comment]
Netherlands is named DutchPublicHoliday
https://github.com/martinjw/Holiday/blob/master/src/PublicHoliday/DutchPublicHoliday.cs

Estonia is there too:
https://github.com/martinjw/Holiday/blob/master/src/PublicHoliday/EstoniaPublicHoliday.cs
