### ISSUE TITLE
Public holidays in the Netherlands - Liberation Day

### ISSUE THREAD

**Issue by sergiu05** [martinjw/Holiday#64]
Hi,

Could you review the implemented rule for _Liberation Day_ - Netherlands?

According with official dutch government and wikipedia sites, _Liberation Day_ is celebrated every year since 1990, and every five years between 1945 and 1989:
- https://www.government.nl/topics/working-hours/question-and-answer/public-holidays-in-the-netherlands 
- https://en.wikipedia.org/wiki/Liberation_Day_(Netherlands)

**Comment by martinjw** [comment]
Fixed in 2.12. Thanks!

**Comment by sergiu05** [comment]
Hello,
Thanks for your fast update.
Small observation: 
 ```
public static DateTime? LiberationDay(int year)
        {
            if (year < 1990 && year % 5 == 0)
            {
                return new DateTime(year, 5, 5);
            }

            return new DateTime(year, 5, 5);
        }
```
This will return a _DateTime_ value for all years less than 1990, because the execution flow will reach the second return statement for the years smaller than 1990 non-divisible by 5 (e.g. 1989, 1988).

An updated version:
```
public static DateTime? LiberationDay(int year)
        {
            if (year >= 1990)
            {
                return new DateTime(year, 5, 5);
            }
            else if (year >= 1945)
            {
                if (year % 5 == 0)
                {
                    return new DateTime(year, 5, 5);
                }
            }
           return null;
        }
```
Could you have a look?
Thanks again,
S.

**Comment by martinjw** [comment]
Thanks @sergiu05 - updated. I won't do an immediate nuget release - I don't think many people will be looking up calendars that old!
