### ISSUE TITLE
Nuget package obsolete

### ISSUE THREAD

**Issue by eric-b** [martinjw/Holiday#7]
Hi,

Thanks for this project. I noted that the package [PublicHoliday](https://www.nuget.org/packages/PublicHoliday/) is up to version 1.3.2. 

Any chance you update it with last version 1.4 containing `SpainPublicHolidays` ?

Thanks

**Comment by martinjw** [comment]
I will be publishing the nuget package in a day or 2

**Comment by martinjw** [comment]
v1.4.0 pushed to nuget.

**Comment by eric-b** [comment]
Thanks a lot :-)
