### ISSUE TITLE
One off 'Day of Mourning' for QEII

### ISSUE THREAD

**Issue by seancallinan** [martinjw/Holiday#71]
Commonwealth countries including the UK, Australia, Canada and New Zealand have announced a one-off 'Day of Mourning' in recognition of the death of Queen Elizabeth II, either falling on the day of her funeral in the UK (19th September 2022) or a day shortly thereafter (22 Sep for Australia, 26 Sep for NZ).

Would it be worth submitting a PR to include these one-off public holidays to allow for users of the library to recognise that these dates are in fact public holidays, or because it's only a one-off in the very near future (and people might not update their libraries quick enough) is it not worth it?

**Comment by martinjw** [comment]
Already done and released for UK. Yes, Ca+Au+NZ need updating.

The official name for UK and Canada, announced last Friday, is "State Funeral of Queen Elizabeth II", but a quick check shows the name in Au + NZ is National Day of Mourning. 

There is likely to be another one off bank holiday for the coronation of Charles III, at least in the UK, but no date is announced yet and it may even be next year,

**Comment by martinjw** [comment]
Released as 2.16.2 on nuget. Thanks!
