### ISSUE TITLE
Incorrect German holidays

### ISSUE THREAD

**Issue by DijanaPenic** [martinjw/Holiday#74]
I've checked holidays for year 2022 and here are my findings:

**June 5th (Pentecost)**
- not returned

**November 16th (Repentance and prayer day)**
 - library returns November 23rd
 
**September 20th (World's children day)**
- library hardcodes it to September 20th, 2019

```
if (this.HasWorldChildrensDay(2019))
    dateTimeList.Add(GermanPublicHoliday.WorldChildrensDay(2019));
```

**July 17th (Easter Sunday)**
- not returned

------------------------------------

Package version: v2.16.2
Tested method: IList<DateTime> PublicHolidays(int year)

**Comment by martinjw** [comment]
Pentecost + Easter Sundays are Sundays, so not normally working days. Checking on this, they are not public holidays in most german Lander - only Brandenburg legally. As a Sunday, it is not useful to include it.

Repentance day had a bad algorithm for first advent. Should be fixed now

Children's Day is fixed too. 

Thanks!

**Comment by martinjw** [comment]
Fixed in https://github.com/martinjw/Holiday/releases/tag/2.17.0.0
