### ISSUE TITLE
SouthAfricaPublicHoliday - Slightly different rules for FixWeekend

### ISSUE THREAD

**Issue by FifoTheHein** [martinjw/Holiday#75]
For the SouthAfricaPublicHoliday implementation, the rules in South Africa are slightly different in that only public holidays that fall on a Sunday are carried over to the following Monday. Public holidays that fall on a Saturday do not get observed on another day.

**Comment by FifoTheHein** [comment]
I have the code fix which I can push to a branch if you allow me to contribute.

**Comment by martinjw** [comment]
Yes, please do a pull request. Remember to add tests!

**Comment by FifoTheHein** [comment]
Perfect, will do.

**Comment by martinjw** [comment]
Thanks! https://github.com/martinjw/Holiday/releases/tag/2.18.0.0
