### ISSUE TITLE
Greek / Orthodox Easter holidays

### ISSUE THREAD

**Issue by pothitos-baikas** [martinjw/Holiday#86]
Is the Greek / Orthodox Easter holidays planned to be implemented? Are they covered otherwise?

**Comment by martinjw** [comment]
Not implemented yet, but could be. We use the Orthodox Easter in the Romanian calendar (PublicHoliday.GetOrthodoxEaster), so that calculator exists already.

**Comment by martinjw** [comment]
In release https://github.com/martinjw/Holiday/releases/tag/2.26.0.0
