### ISSUE TITLE
Exception thrown when getting the holidays for Turkey in 2023

### ISSUE THREAD

**Issue by ahmet-cetinkaya** [martinjw/Holiday#87]
When getting the PublicHolidayNames(2023) for Turkey, this exception is thrown:
`An item with the same key has already been added. Key: 4/23/2023 12:00:00 AM`

Reason:
Because National Sovereignty and Children's Day coincides with the 3rd day of Ramadan Feast.

**Comment by martinjw** [comment]
Candidate release https://github.com/martinjw/Holiday/releases/tag/2.27.0.0

Note I found a bug with the conversion between Hijri years, which would appear in 2024 and 2025- see the tests and reworked logic for Ramadan and Feast of the Sacrifice.

**Comment by martinjw** [comment]
Final release https://github.com/martinjw/Holiday/releases/tag/2.27.0.9
