### ISSUE TITLE
the method IsPublicHoliday in DenmarkPublicHoliday does find easter Holidays if they are in march

### ISSUE THREAD

**Issue by OscarItm** [martinjw/Holiday#91]

**Comment by martinjw** [comment]
Next March Easter is 2024. This test works. Do you have a specific date that fails?
```c#
            var expected = new DateTime(2024, 3, 31);
            var actual = DenmarkPublicHoliday.Easter(2024);
            Assert.AreEqual(expected, actual);
            Assert.IsTrue(new DenmarkPublicHoliday().IsPublicHoliday(expected));
```

**Comment by OscarItm** [comment]
The following function has no holidays if the month is 3(march) and as your test shows sometimes easter is in march
 public override bool IsPublicHoliday(DateTime dt)
        {
            int year = dt.Year;
            DateTime date = dt.Date;
            switch (dt.Month)
            {
                case 1:
                    if (NewYear(year) == date)
                    {
                        return true;
                    }

                    break;
                case 3:
                case 4:
                    if (MaundyThursday(year) == date)
                    {
                        return true;
                    }
if (GoodFriday(year) == date)
                    {
                        return true;
                    }

                    if (HolidayCalculator.GetEaster(year) == date)
                    {
                        return true;
                    }

                    if (EasterMonday(year) == date)
                    {
                        return true;
                    }
