### ISSUE TITLE
Queens Birthday doesn't seem to work?

### ISSUE THREAD

**Issue by dotnetshadow** [martinjw/Holiday#92]
Hi there, 

I just had a chance to try the library out with the new "king" support but I don't know if it's working

I seem to get only Queens Birthday as the name, am I doing something wrong?
![image](https://user-images.githubusercontent.com/296247/225607352-9c59d7c8-6735-4610-9c27-02ccc72a180d.png)

_Originally posted by @dotnetshadow in https://github.com/martinjw/Holiday/issues/84#issuecomment-1471806052_

**Comment by martinjw** [comment]
I created  a new console, referenced the nuget and it seems to work...
![image](https://user-images.githubusercontent.com/2040281/230887229-ac075447-470c-48ca-b4b0-f26ac0fb8b75.png)

**Comment by dotnetshadow** [comment]
Hi there, 

I just checked the latest version (2.227),  it works correctly,

I think [2.25.0.3](https://github.com/martinjw/Holiday/releases/tag/2.25.0.3) must of had an issue
